select
    business_id,
    source_type,
    source_id,
    account_id,
    account_name,
    campaign_id,
    campaign_name,
    ad_group_id,
    ad_group_name,
    ad_id,
    ad_name,
    report_date,
    reporting_timezone,
    currency,
    spend as spend_usd,
    impressions,
    reach,
    frequency,
    clicks as destination_clicks,
    platform_conversions,
    link_clicks,
    video_views,
    (details_json::jsonb ->> 'checkouts_initiated')::double precision as checkouts,
    (details_json::jsonb ->> 'hook_rate')::double precision as hook_rate,
    (details_json::jsonb ->> 'hold_rate')::double precision as hold_rate,
    (details_json::jsonb ->> 'video_views_6s')::bigint as video_views_6s,
    (details_json::jsonb ->> 'video_views_25pct')::bigint as video_views_25pct,
    (details_json::jsonb ->> 'video_views_50pct')::bigint as video_views_50pct,
    (details_json::jsonb ->> 'video_views_75pct')::bigint as video_views_75pct,
    (details_json::jsonb ->> 'video_views_100pct')::bigint as video_views_100pct,
    (details_json::jsonb ->> 'platform_reported_purchase_roas')::double precision
        as platform_reported_purchase_roas,
    clicks::double precision / nullif(impressions, 0) as destination_ctr,
    spend::double precision / nullif(clicks, 0) as destination_cpc_usd,
    spend::double precision / nullif(platform_conversions, 0) as platform_cpa_usd
from {{ source('analytics', 'sama_pilot_tiktok_ad_daily') }}
